//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationTests.Areas.Reports.Views.Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReportsViewTestsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportsViewTestsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntegrationTests.Areas.Reports.Views.Reports.ReportsViewTestsResources", typeof(ReportsViewTestsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;\r\n&lt;head&gt;\r\n\t&lt;title&gt;&lt;/title&gt;\r\n&lt;/head&gt;\r\n&lt;body&gt;\r\n&lt;p&gt;&lt;a href=\&quot;javascript:window.print()\&quot;&gt;&lt;u&gt;Print this page&lt;/u&gt;&lt;/a&gt;&lt;/p&gt;\r\n\r\n&lt;address&gt;{name}&lt;br /&gt;\r\n{address} {csz}&lt;br /&gt;\r\n{email}&lt;br /&gt;\r\nH {homephone}&lt;br /&gt;\r\nC {cellphone}&lt;br /&gt;\r\nDate of Birth: {dob}&lt;br /&gt;\r\n&lt;br /&gt;\r\nApplication complete date: {extradate:App:Completed}&lt;/address&gt;\r\n\r\n&lt;h4&gt;GENERAL INFORMATION&lt;/h4&gt;\r\n\r\n&lt;p&gt;Redeemer Congregation&lt;/p&gt;\r\n\r\n&lt;p&gt;{smallgroup:[Downtown]}{smallgroup:[East Side]}{smallgroup:[West Side]}{s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidHtmlContent {
            get {
                return ResourceManager.GetString("ValidHtmlContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Settings id=&quot;1&quot;&gt;&lt;Confirmation&gt;&lt;Subject&gt;Confirmation for Redeemer Membership Application&lt;/Subject&gt;&lt;Body&gt;&amp;lt;h4&amp;gt;GENERAL INFORMATION&amp;lt;/h4&amp;gt;&amp;lt;div class=&quot;&quot;question&quot;&quot;&amp;gt;Vow 1 reads: &amp;amp;quot;Do you acknowledge yourself to be a sinner in the sight of God, justly deserving his displeasure and without hope except through his sovereign mercy?&amp;amp;quot;&amp;lt;/div&amp;gt;&amp;lt;div class=&quot;&quot;answer&quot;&quot;&amp;gt;{regtext:Vow 1 reads: &amp;amp;quot;Do you acknowledge yourself to be a sinner in the sight of God, justly deserving his [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XMLSettings {
            get {
                return ResourceManager.GetString("XMLSettings", resourceCulture);
            }
        }
    }
}
