//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsDataTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CmsDataTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print (str([
        ///    model.docusign.ApiClient() is None,
        ///    model.docusign.Configuration() is None,
        ///    model.docusign.Document() is None,
        ///    model.docusign.EnvelopeDefinition() is None,
        ///    model.docusign.EnvelopesApi() is None,
        ///    model.docusign.EnvelopesApi(&quot;https://localhost/&quot;) is None,
        ///    model.docusign.ListStatusChangesOptions() is None,
        ///    model.docusign.Recipients() is None,
        ///    model.docusign.RecipientViewRequest() is None,
        ///    model.docusign.Signer() is None,
        ///    model.docusign.SignHer [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DocusignApiTest {
            get {
                return ResourceManager.GetString("DocusignApiTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;10/17/2019 - 11/27/2019&lt;/p&gt;
        ///    &lt;p&gt;11/13/2019 12:00:00 AM&lt;/p&gt;
        ///    &lt;p&gt;CC&lt;/p&gt;
        ///    &lt;p&gt;Test Template Org&lt;/p&gt;
        ///    &lt;p&gt;1234-567890&lt;/p&gt;
        ///    &lt;p&gt;99.95&lt;/p&gt;
        ///    &lt;p&gt;102,938.67&lt;/p&gt;
        ///    &lt;p&gt;11/14/2019 12:00:00 AM&lt;/p&gt;
        ///    &lt;p&gt;ACH&lt;/p&gt;
        ///    &lt;p&gt;Some Other Org&lt;/p&gt;
        ///    &lt;p&gt;1234-XXXXXX&lt;/p&gt;
        ///    &lt;p&gt;109.00&lt;/p&gt;
        ///    &lt;p&gt;360.00&lt;/p&gt;
        ///.
        /// </summary>
        public static string RenderTemplateResults {
            get {
                return ResourceManager.GetString("RenderTemplateResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;{{header.DateFrom}} - &lt;p&gt;{{header.DateTo}}&lt;/p&gt;
        ///{{#each results}}
        ///    &lt;p&gt;{{trans_date}}&lt;/p&gt;
        ///    &lt;p&gt;{{Payment_Type}}&lt;/p&gt;
        ///    &lt;p&gt;{{OrganizationName}}&lt;/p&gt;
        ///    &lt;p&gt;{{account_code}}&lt;/p&gt;
        ///    &lt;p&gt;{{Fmt Amount &quot;N2&quot;}}&lt;/p&gt;
        ///    &lt;p&gt;{{Fmt total_amt &quot;N2&quot;}}&lt;/p&gt;
        ///{{/each}}
        ///.
        /// </summary>
        public static string RenderTemplateTest {
            get {
                return ResourceManager.GetString("RenderTemplateTest", resourceCulture);
            }
        }
    }
}
