//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsWeb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CmsWeb.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {name},
        ///&lt;p&gt;Your username is: {username}&lt;/p&gt;
        ///&lt;p&gt;If you did not request this, please disregard this message.&lt;/p&gt;
        ///&lt;p&gt;Thanks,&lt;br /&gt;
        ///The bvCMS Team&lt;/p&gt;
        ///.
        /// </summary>
        public static string AccountController_ForgotUsername {
            get {
                return ResourceManager.GetString("AccountController_ForgotUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Someone recently requested a new password for this email address {email}.  
        ///However, we could not find an account associated with this email address.
        ///You may try a different email address, or contact the church.&lt;/p&gt;
        ///&lt;p&gt;If this is a mistake, please disregard this message, your password will not be changed.&lt;/p&gt;
        ///&lt;p&gt;Thanks,&lt;br /&gt;
        ///The BVCMS Team&lt;/p&gt;
        ///.
        /// </summary>
        public static string AccountModel_ForgotPasswordBadEmail {
            get {
                return ResourceManager.GetString("AccountModel_ForgotPasswordBadEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Someone recently requested a new password for this email address {email}.
        ///To set your password, click the link below:&lt;/p&gt;
        ///&lt;blockquote&gt;&lt;a href=&quot;{resetlink}&quot;&gt;New Password&lt;/a&gt;&lt;/blockquote&gt;
        ///&lt;p&gt;If this is a mistake, please disregard this message, your password will not be changed.&lt;/p&gt;
        ///&lt;p&gt;Thanks,&lt;br /&gt;
        ///The BVCMS Team&lt;/p&gt;
        ///.
        /// </summary>
        public static string AccountModel_ForgotPasswordReset {
            get {
                return ResourceManager.GetString("AccountModel_ForgotPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Someone recently requested a new password for {email}.
        ///To set your password, click your username below:&lt;/p&gt;
        ///&lt;blockquote&gt;{resetlink}&lt;/blockquote&gt;
        ///&lt;p&gt;If this is a mistake, please disregard this message, your password will not be changed.&lt;/p&gt;
        ///&lt;p&gt;Thanks,&lt;br /&gt;
        ///The BVCMS Team&lt;/p&gt;
        ///.
        /// </summary>
        public static string AccountModel_ForgotPasswordReset2 {
            get {
                return ResourceManager.GetString("AccountModel_ForgotPasswordReset2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {name},
        ///&lt;p&gt;You have a new account on our Church Management System. 
        ///Click on your username below to set your password and login to the system.&lt;/p&gt;
        ///&lt;blockquote&gt;
        ///&lt;h3&gt;Your username is: &lt;b&gt;&lt;a href=&quot;{link}&quot;&gt;{username}&lt;/a&gt;&lt;/h3&gt;
        ///&lt;/blockquote&gt;.
        /// </summary>
        public static string AccountModel_NewUserWelcome {
            get {
                return ResourceManager.GetString("AccountModel_NewUserWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;TestPlan&gt;
        ///  &lt;Sections&gt;
        ///    &lt;Section name=&quot;Meta&quot;&gt;
        ///      &lt;Tests&gt;
        ///        &lt;test name=&quot;Lookup&quot;&gt;
        ///          &lt;args&gt;
        ///            &lt;name&gt;table&lt;/name&gt;
        ///          &lt;/args&gt;
        ///          &lt;script&gt;
        ///            &lt;![CDATA[
        ///xml = webclient.DownloadString(&apos;APIMeta/lookups/&apos; + table)
        ///return xml
        ///]]&gt;
        ///          &lt;/script&gt;
        ///          &lt;description&gt;
        ///            &lt;![CDATA[
        ///&lt;ul&gt;
        ///&lt;li&gt;These are tables of id / value pairs for look up tables&lt;/li&gt;
        ///&lt;li&gt;Try MemberStatus as a name of a table&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string APITestPlan {
            get {
                return ResourceManager.GetString("APITestPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {	
        ///Comment: &quot;Gives a table 7.5 inches wide suitable for 8x11 portrait&quot;,
        ///PageHeight: 11,
        ///PageWidth: 8.5,
        ///MarginLeft: .5,
        ///MarginRight: .5,
        ///MarginTop: .5,
        ///MarginBottom: .5,
        ///RowHeight: 1.2,
        ///SpacerWidth: 0.04,
        ///LabelWidth: 2.5,
        ///PicWidth: .67,
        ///PicWidthPixels: 62,
        ///FontSizeName: 12,
        ///FontSize: 10,
        ///FontSizeEmail: 9 
        ///}.
        /// </summary>
        public static string CompactDirectoryParameters {
            get {
                return ResourceManager.GetString("CompactDirectoryParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	Comment: &quot;Gives a table 4.9 inches wide suitable for bi-fold booklet landscape (2 pages per sheet)&quot;,
        ///	PageHeight: 11,
        ///	PageWidth: 8.5,
        ///	MarginLeft: .3,
        ///	MarginRight: .3,
        ///	MarginTop: .4,
        ///	MarginBottom: .4,
        ///	RowHeight: .96,
        ///	SpacerWidth: 0.04,
        ///	LabelWidth: 1.6333,
        ///	PicWidth: .55,
        ///	PicWidthPixels: 50,
        ///	FontSizeName: 7.5,
        ///	FontSize: 7,
        ///	FontSizeEmail: 5.5
        ///}.
        /// </summary>
        public static string CompactDirectoryParameters2 {
            get {
                return ResourceManager.GetString("CompactDirectoryParameters2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TouchPoint Software, Inc..
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for managing your subscriptions to {org}&lt;br/&gt;
        ///You have the following subscriptions:&lt;br/&gt;
        ///{details}.
        /// </summary>
        public static string ConfirmSubscriptions {
            get {
                return ResourceManager.GetString("ConfirmSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///with ids as (
        ///	select * from dbo.Contributions2SearchIds(@json)
        ///)
        ///select 
        ///	p.FamilyId,
        ///	p.PeopleId,
        ///    c.ContributionDate as [Date],
        ///    
        ///    case when fa.HeadOfHouseholdId = sp.PeopleId
        ///			and isnull(sp.ContributionOptionsId, case when mssp.Married = 1 then 2 else 1 end) = 2
        ///			and isnull(p.ContributionOptionsId, case when msp.Married = 1 then 2 else 1 end) = 2
        ///		then sp.PeopleId 
        ///		else c.PeopleId 
        ///	end as CreditGiverId,
        ///
        ///    case when isnull(sp.ContributionOptionsId, case when mssp.Marr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContributionsController_ContributionsAdvancedSearch_ {
            get {
                return ResourceManager.GetString("ContributionsController_ContributionsAdvancedSearch_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Sample Church&lt;/h1&gt;
        ///&lt;h2&gt;2000 Appling Rd. | Cordova | TN 38088-1210 | (901) 347-2000&lt;/h2&gt;.
        /// </summary>
        public static string ContributionStatementHeader {
            get {
                return ResourceManager.GetString("ContributionStatementHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;i&gt;
        ///NOTE: No goods or services were provided to you by the church in connection with any contibution;
        ///any value received consisted entirely of intangible religious benefits.
        ///Sample Church, FEIN # 1234, is a 501(c)(3) organization and
        ///qualifies as a part of the Southern Baptist Convention&apos;s group tax exemption ruling number GEN #1674.
        ///&lt;/i&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;i&gt;
        ///Thank you for your faithfulness in the giving of your time, talents, and resources. Together we can share the love of Jesus with our city.
        ///&lt;/i&gt;&lt;/p&gt;.
        /// </summary>
        public static string ContributionStatementNotice {
            get {
                return ResourceManager.GetString("ContributionStatementNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {name},
        ///&lt;p&gt;We noticed you already have an account in our church database.&lt;/p&gt;
        ///&lt;p&gt;You can login at &lt;a href=&quot;{host}&quot;&gt;{host}&lt;/a&gt;. 
        ///And if you can&apos;t remember your password or username, click the Forgot Password link when you get there. 
        ///Note: you will need to know your username for this to work. If you do not know your username, then please click forgot username first.
        ///This will send you a link you can use to reset your password.&lt;/p&gt;
        ///&lt;p&gt;You can use your account to help us maintain your correct address, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CreateAccount_ExistingUser {
            get {
                return ResourceManager.GetString("CreateAccount_ExistingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;CustomColumns&gt;
        ///  &lt;Joins&gt;
        ///    &lt;join name=&quot;g&quot;&gt;
        ///      LEFT JOIN lookup.Gender g ON g.Id = p.GenderId
        ///    &lt;/join&gt;
        ///    &lt;join name=&quot;mars&quot;&gt;
        ///      LEFT JOIN lookup.MaritalStatus mars ON mars.Id = p.MaritalStatusId
        ///    &lt;/join&gt;
        ///    &lt;join name=&quot;fp&quot;&gt;
        ///      LEFT JOIN lookup.FamilyPosition fp ON fp.Id = p.PositionInFamilyId
        ///    &lt;/join&gt;
        ///    &lt;join name=&quot;rr&quot;&gt;
        ///      LEFT JOIN dbo.recreg rr ON rr.peopleid = p.peopleid
        ///    &lt;/join&gt;
        ///    &lt;join name=&quot;mo&quot;&gt;
        ///      LEFT JOIN dbo.people mo ON mo.familyid = p.familyid  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CustomColumns {
            get {
                return ResourceManager.GetString("CustomColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {name},
        ///&lt;p&gt;You registered for {org} using a different email address than the one we have on record.
        ///It is important that you call the church &lt;strong&gt;{phone}&lt;/strong&gt; to update our records
        ///so that you will receive future important notices regarding this registration.&lt;/p&gt;.
        /// </summary>
        public static string DiffEmailMessage {
            get {
                return ResourceManager.GetString("DiffEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DocxAveryLabel {
            get {
                object obj = ResourceManager.GetObject("DocxAveryLabel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DocxRollsheet {
            get {
                object obj = ResourceManager.GetObject("DocxRollsheet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;InvolvementTable&gt;
        ///  &lt;Columns&gt;
        ///	&lt;Column field=&quot;Organization&quot; sortable=&quot;true&quot; /&gt;
        ///	&lt;Column field=&quot;Leader&quot; /&gt;
        ///	&lt;Column field=&quot;Enroll Date&quot; sortable=&quot;true&quot;  /&gt;
        ///	&lt;Column field=&quot;MemberType&quot; /&gt;
        ///	&lt;Column field=&quot;AttendPct&quot; /&gt;
        ///  &lt;/Columns&gt;
        ///&lt;/InvolvementTable&gt;.
        /// </summary>
        public static string InvolvementTableCurrent {
            get {
                return ResourceManager.GetString("InvolvementTableCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;InvolvementTable&gt;
        ///  &lt;Columns&gt;
        ///	&lt;Column field=&quot;Organization&quot; /&gt;
        ///	&lt;Column field=&quot;Enroll Date&quot; /&gt;
        ///	&lt;Column field=&quot;MemberType&quot; /&gt;
        ///	&lt;Column field=&quot;Location&quot; /&gt;
        ///	&lt;Column field=&quot;Leader&quot; /&gt;
        ///	&lt;Column field=&quot;Schedule&quot; /&gt;
        ///  &lt;/Columns&gt;
        ///&lt;/InvolvementTable&gt;.
        /// </summary>
        public static string InvolvementTablePending {
            get {
                return ResourceManager.GetString("InvolvementTablePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;InvolvementTable&gt;
        ///  &lt;Columns&gt;
        ///	&lt;Column field=&quot;Organization&quot; sortable=&quot;true&quot; /&gt;
        ///	&lt;Column field=&quot;Enroll Date&quot; sortable=&quot;true&quot; /&gt;
        ///	&lt;Column field=&quot;Drop Date&quot; sortable=&quot;true&quot; /&gt;
        ///	&lt;Column field=&quot;MemberType&quot; /&gt;
        ///	&lt;Column field=&quot;AttendPct&quot; /&gt;
        ///  &lt;/Columns&gt;
        ///&lt;/InvolvementTable&gt;.
        /// </summary>
        public static string InvolvementTablePrevious {
            get {
                return ResourceManager.GetString("InvolvementTablePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {name},
        ///&lt;p&gt;You registered for {org}, and we found your record, 
        ///but there was no email address on your Existing record in our database.
        ///If you would like for us to update your record with this email address or another,
        ///Please contact the church at &lt;strong&gt;{phone}&lt;/strong&gt; to let us know.
        ///It is important that we have your email address so that
        ///you will receive future important notices regarding this registration.
        ///But we won&apos;t add that to your record without your permission.
        ///
        ///Thank you&lt;/p&gt;.
        /// </summary>
        public static string NoEmailMessage {
            get {
                return ResourceManager.GetString("NoEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {name},
        ///&lt;p&gt;It appears that you created a user account from your mobile device. 
        ///We found your existing record but you used this email address &apos;{otheremail}&apos; which is not the one we have your record.
        ///We went ahead and created a new account for you. However, it is a separate one from your existing account.
        ///You should have also received a welcome message for that new account.&lt;/p&gt;
        ///&lt;p&gt;It is important that you contact the church at &lt;strong&gt;{churchphone}&lt;/strong&gt; to update your records
        ///so that your data w [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NotifyDuplicateUserOnMobile {
            get {
                return ResourceManager.GetString("NotifyDuplicateUserOnMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    &lt;h2&gt;Transaction Completed&lt;/h2&gt;
        ///    &lt;p style=&apos;color: Black&apos;&gt;
        ///        Thank you, your transaction is complete for {org}.
        ///        You should receive a confirmation email at {email} shortly.&lt;br /&gt;&lt;br /&gt;
        ///    &lt;/p&gt;
        ///    &lt;p style=&apos;color: Blue&apos;&gt;&lt;a href=&apos;{url}&apos;&gt;Start a New Transaction&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string OnlineRegModel_ThankYouMessage {
            get {
                return ResourceManager.GetString("OnlineRegModel_ThankYouMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;{name},&lt;/p&gt;
        ///&lt;p&gt;You have been assigned to {org} in room {room}. The leader&apos;s name is {leader}.&lt;/p&gt;
        ///&lt;p&gt;Please call {phone} if you have any questions.&lt;/p&gt;
        ///&lt;p&gt;Please print this and bring it with you as a reminder of your room number.&lt;/p&gt;
        ///&lt;p&gt;Thank you!&lt;br/&gt;
        ///{church}&lt;/p&gt;.
        /// </summary>
        public static string OrgMembersModel_SendMovedNotices {
            get {
                return ResourceManager.GetString("OrgMembersModel_SendMovedNotices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;OrgSearch&gt;
        ///  &lt;Fields&gt;
        ///	&lt;Field&gt;Name&lt;/Field&gt;
        ///	&lt;Field dropdown=&quot;true&quot; label=&quot;Organization Type&quot;&gt;TypeId&lt;/Field&gt;
        ///	&lt;Field dropdown=&quot;true&quot; label=&quot;Program&quot;&gt;ProgramId&lt;/Field&gt;
        ///	&lt;Field dropdown=&quot;true&quot; label=&quot;Division&quot;&gt;DivisionId&lt;/Field&gt;
        ///	&lt;Field dropdown=&quot;true&quot; label=&quot;Status&quot;&gt;StatusId&lt;/Field&gt;
        ///	&lt;Field dropdown=&quot;true&quot; label=&quot;Campus&quot;&gt;CampusId&lt;/Field&gt;
        ///	&lt;Field dropdown=&quot;true&quot; label=&quot;Schedule&quot;&gt;ScheduleId&lt;/Field&gt;
        ///	&lt;Field dropdown=&quot;true&quot; label=&quot;Online Registration&quot;&gt;OnlineReg&lt;/F [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrgSearchFields {
            get {
                return ResourceManager.GetString("OrgSearchFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --default.v1   IMPORTANT! delete this line if you want to customize, otherwise your changes will be overwritten
        ///SELECT
        ///	p.PeopleId,
        ///	p.LastName,
        ///	p.FamilyId,
        ///	Name = p.Name2,
        ///	p.PreferredName,
        ///	Suffix = p.SuffixCode,
        ///	DOB = dbo.DOB(p.BirthMonth,p.BirthDay, p.BirthYear),
        ///	[Address] = p.PrimaryAddress,
        ///	Address2 = p.PrimaryAddress2,
        ///	City = p.PrimaryCity,
        ///	[State] = p.PrimaryState,
        ///	Zip = p.PrimaryZip,
        ///	Cell = p.CellPhone,
        ///	Home = p.HomePhone,
        ///	Email = p.EmailAddress,
        ///	Email2 = p.EmailAddress [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PictureDirectorySql {
            get {
                return ResourceManager.GetString("PictureDirectorySql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--default.v1   IMPORTANT! delete this line if you want to customize, otherwise your changes will be overwritten--&gt;
        ///&lt;div id=&quot;results&quot;&gt;
        ///  &lt;style&gt;
        ///    .profile-portrait {
        ///      height: 75px;
        ///      width: 75px;
        ///      display: inline-block;
        ///      background-repeat: no-repeat;
        ///      background-size: cover;
        ///    }
        ///    .profile-photo {
        ///      display: inline-block;
        ///      margin-bottom: 10px;
        ///      border-radius: 999999px;
        ///      background-color: #fff;
        ///      border: 1px solid #e6e6e6;
        ///      padding-t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PictureDirectoryTemplate {
            get {
                return ResourceManager.GetString("PictureDirectoryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///  The following meetings are ready to be viewed:&lt;br /&gt;
        ///  {{#each this}}
        ///    &lt;a href=&apos;{{ServerLink}}/Meeting/{{MeetingId}}&apos;&gt;{{OrgName}} - {{LastMeeting}}&lt;/a&gt;&lt;br /&gt;
        ///  {{/each}}
        ///  {{#each this}}
        ///    {{#if HasAbsents}}
        ///      &lt;h2&gt;Recent Absents&lt;/h2&gt;
        ///      &lt;hr /&gt;
        ///      &lt;a href=&apos;{{ServerLink}}/Org/{{OrganizationId}}&apos;&gt;{{OrgName}}&lt;/a&gt; ({{LeaderName}})&lt;br /&gt;
        ///      &lt;span&gt;
        ///        Members with ({{ConsecutiveAbsentsThreshold}})
        ///        or more consecutive absents on and before {{Fmt LastMeeting &quot;d&quot;}}
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RecentVisitsAbsents {
            get {
                return ResourceManager.GetString("RecentVisitsAbsents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ReportsMenu&gt;
        ///  &lt;Header excludedRoles=&quot;OrgLeadersOnly&quot;&gt;Statistics&lt;/Header&gt;
        ///  &lt;Report excludedRoles=&quot;OrgLeadersOnly&quot; link=&quot;/Reports/VitalStats&quot;&gt;Vital Stats&lt;/Report&gt;
        ///  &lt;Report excludedRoles=&quot;OrgLeadersOnly&quot; link=&quot;/Figures/Figures/Index&quot;&gt;Vital Stats Graphs&lt;/Report&gt;
        ///  &lt;Header&gt;Attendance Summary&lt;/Header&gt;
        ///  &lt;Report link=&quot;/Reports/ChurchAttendance&quot; target=&quot;_blank&quot;&gt;Week at a Glance&lt;/Report&gt;
        ///  &lt;Report link=&quot;/Reports/ChurchAttendance2&quot; target=&quot;_blank&quot;&gt;Average Week at a Gl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportsMenu {
            get {
                return ResourceManager.GetString("ReportsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {first}
        ///&lt;p&gt;Here is your confirmation for {org}.&lt;/p&gt;
        ///DETAILS: &lt;br/&gt;
        ///{details}
        ///&lt;p&gt;
        ///Your Ministry Team for {org}
        ///&lt;/p&gt;.
        /// </summary>
        public static string SettingsRegistrationModel_DefaulConfirmation {
            get {
                return ResourceManager.GetString("SettingsRegistrationModel_DefaulConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hi {first},&lt;/p&gt;
        ///
        ///&lt;p&gt;I need a substitute for {org}&lt;br&gt;
        ///
        ///on {meetingdate} at {meetingtime}&lt;/p&gt;
        ///
        ///&lt;p&gt;DO NOT REPLY. Instead, click one of the links below.&lt;/p&gt;
        ///&lt;blockquote&gt;
        ///
        ///&lt;p&gt;{yeslink}&lt;/p&gt;
        ///
        ///&lt;p&gt;{nolink}&lt;/p&gt;
        ///
        ///&lt;/blockquote&gt;
        ///
        ///&lt;p&gt;
        ///Thank you for your consideration,&lt;br /&gt;
        ///
        ///{sendername}
        ///&lt;/p&gt;.
        /// </summary>
        public static string VolSubModel_ComposeMessage_Body {
            get {
                return ResourceManager.GetString("VolSubModel_ComposeMessage_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;p&gt;{substitute},&lt;/p&gt;
        ///&lt;p&gt;Thank you so much.&lt;/p&gt;
        ///&lt;p&gt;You are now assigned to cover for {requestor}&lt;br /&gt;
        ///in the {org}&lt;br /&gt;
        ///on {meetingdate} at {meetingtime}.
        ///See you there!&lt;/p&gt;.
        /// </summary>
        public static string VolSubModel_VolunteerSubConfirm {
            get {
                return ResourceManager.GetString("VolSubModel_VolunteerSubConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;p&gt;Hi {first},&lt;/p&gt;
        ///&lt;p&gt;We need additional volunteers for {org}&lt;br&gt;
        ///on {meetingdate} at {meetingtime}&lt;/p&gt;
        ///
        ///&lt;p&gt;DO NOT REPLY. Instead, click one of the links below.&lt;/p&gt;
        ///&lt;blockquote&gt;
        ///&lt;p&gt;{yeslink}&lt;/p&gt;
        ///&lt;p&gt;{nolink}&lt;/p&gt;
        ///&lt;/blockquote&gt;
        ///&lt;p&gt;
        ///Thank you for your consideration,&lt;br /&gt;
        ///{sendername}
        ///&lt;/p&gt;.
        /// </summary>
        public static string VolunteerRequestModel_ComposeMessage_Body {
            get {
                return ResourceManager.GetString("VolunteerRequestModel_ComposeMessage_Body", resourceCulture);
            }
        }
    }
}
