CREATE NONCLUSTERED INDEX [_dta_index_People_6_1770345967__K1_K92_50_55] ON [dbo].[People] ([PeopleId], [ContributionOptionsId]) INCLUDE ([FirstName], [NickName])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
