CREATE TABLE [dbo].[Preferences]
(
[UserId] [int] NOT NULL,
[Preference] [nvarchar] (30) NOT NULL,
[Value] [nvarchar] (50) NULL
)
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
