ALTER TABLE [dbo].[OrgMemMemTags] ADD CONSTRAINT [PK_OrgMemMemTags] PRIMARY KEY CLUSTERED  ([OrgId], [PeopleId], [MemberTagId])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
