ALTER TABLE [dbo].[EmailOptOut] ADD CONSTRAINT [PK_EmailOptOut_1] PRIMARY KEY CLUSTERED  ([ToPeopleId], [FromEmail])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
