CREATE TABLE [dbo].[EmailToText]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[Carrier] [nvarchar] (50) NULL,
[domain] [nvarchar] (50) NULL
)
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
