ALTER TABLE [dbo].[Query] ADD CONSTRAINT [PK_Query_1] PRIMARY KEY CLUSTERED  ([QueryId])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
