CREATE FUNCTION [dbo].[LastActive] (@uid INT)
RETURNS DATETIME
AS
	BEGIN
	DECLARE @dt DATETIME
		SELECT @dt = MAX(a.ActivityDate) 
		FROM dbo.ActivityLog a
		WHERE @uid = a.UserId
	RETURN @dt
	END


GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
