CREATE TABLE [dbo].[PrintJob]
(
[Id] [nvarchar] (50) NOT NULL,
[Stamp] [datetime] NOT NULL,
[Data] [nvarchar] (max) NULL
)
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
