ALTER TABLE [dbo].[CheckInActivity] ADD CONSTRAINT [FK_CheckInActivity_CheckInTimes] FOREIGN KEY ([Id]) REFERENCES [dbo].[CheckInTimes] ([Id])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
