ALTER TABLE [dbo].[SMSItems] ADD CONSTRAINT [FK_SMSItems_People] FOREIGN KEY ([PeopleID]) REFERENCES [dbo].[People] ([PeopleId])
ALTER TABLE [dbo].[SMSItems] ADD CONSTRAINT [FK_SMSItems_SMSList] FOREIGN KEY ([ListID]) REFERENCES [dbo].[SMSList] ([ID])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
