ALTER TABLE [dbo].[SMSList] ADD CONSTRAINT [FK_SMSList_People] FOREIGN KEY ([SenderID]) REFERENCES [dbo].[People] ([PeopleId])
GO
ALTER TABLE [dbo].[SMSList] ADD CONSTRAINT [FK_SMSList_SMSGroups] FOREIGN KEY ([SendGroupID]) REFERENCES [dbo].[SMSGroups] ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
