ALTER TABLE [dbo].[SMSItems] ADD CONSTRAINT [FK_SMSItems_People] FOREIGN KEY ([PeopleID]) REFERENCES [dbo].[People] ([PeopleId])
GO
ALTER TABLE [dbo].[SMSItems] ADD CONSTRAINT [FK_SMSItems_SMSList] FOREIGN KEY ([ListID]) REFERENCES [dbo].[SMSList] ([ID])
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
