CREATE PROCEDURE [dbo].[DropOrgMember](@oid INT, @pid INT)
AS
BEGIN
	DECLARE @tranid INT 
	DECLARE @dropdate DATETIME = GETDATE()
	EXEC @tranid = dbo.DropOrgMemberAddET @oid, @pid, @dropdate
	RETURN @tranid
END
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
