CREATE NONCLUSTERED INDEX [_dta_index_Attend_283_104960046__K5_K1_4] ON [dbo].[Attend] ([AttendanceFlag], [PeopleId]) INCLUDE ([MeetingDate])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
