CREATE TABLE [dbo].[Roles]
(
[RoleName] [nvarchar] (50) NULL,
[RoleId] [int] NOT NULL IDENTITY(1, 1),
[hardwired] [bit] NULL
)
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
