ALTER TABLE [dbo].[Contact] ADD CONSTRAINT [PK_Contacts] PRIMARY KEY CLUSTERED  ([ContactId])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
