CREATE TABLE [dbo].[People]
(
[PeopleId] [int] NOT NULL IDENTITY(1, 1),
[CreatedBy] [int] NOT NULL,
[CreatedDate] [datetime] NULL,
[DropCodeId] [int] NOT NULL,
[GenderId] [int] NOT NULL CONSTRAINT [DF_PEOPLE_TBL_GENDER_ID] DEFAULT ((0)),
[DoNotMailFlag] [bit] NOT NULL CONSTRAINT [DF_PEOPLE_TBL_DO_NOT_MAIL_FLAG] DEFAULT ((0)),
[DoNotCallFlag] [bit] NOT NULL CONSTRAINT [DF_PEOPLE_TBL_DO_NOT_CALL_FLAG] DEFAULT ((0)),
[DoNotVisitFlag] [bit] NOT NULL CONSTRAINT [DF_PEOPLE_TBL_DO_NOT_VISIT_FLAG] DEFAULT ((0)),
[AddressTypeId] [int] NOT NULL CONSTRAINT [DF_PEOPLE_TBL_ADDRESS_TYPE_ID] DEFAULT ((10)),
[PhonePrefId] [int] NOT NULL CONSTRAINT [DF_PEOPLE_TBL_PHONE_PREF_ID] DEFAULT ((10)),
[MaritalStatusId] [int] NOT NULL,
[PositionInFamilyId] [int] NOT NULL,
[MemberStatusId] [int] NOT NULL,
[FamilyId] [int] NOT NULL,
[BirthMonth] [int] NULL,
[BirthDay] [int] NULL,
[BirthYear] [int] NULL,
[OriginId] [int] NULL,
[EntryPointId] [int] NULL,
[InterestPointId] [int] NULL,
[BaptismTypeId] [int] NULL,
[BaptismStatusId] [int] NULL,
[DecisionTypeId] [int] NULL,
[NewMemberClassStatusId] [int] NULL,
[LetterStatusId] [int] NULL,
[JoinCodeId] [int] NOT NULL CONSTRAINT [DF_PEOPLE_TBL_JOIN_CODE_ID] DEFAULT ((0)),
[EnvelopeOptionsId] [int] NULL,
[BadAddressFlag] [bit] NULL,
[ResCodeId] [int] NULL,
[AddressFromDate] [datetime] NULL,
[AddressToDate] [datetime] NULL,
[WeddingDate] [datetime] NULL,
[OriginDate] [datetime] NULL,
[BaptismSchedDate] [datetime] NULL,
[BaptismDate] [datetime] NULL,
[DecisionDate] [datetime] NULL,
[LetterDateRequested] [datetime] NULL,
[LetterDateReceived] [datetime] NULL,
[JoinDate] [datetime] NULL,
[DropDate] [datetime] NULL,
[DeceasedDate] [datetime] NULL,
[TitleCode] [nvarchar] (10) NULL,
[FirstName] [nvarchar] (25) NULL,
[MiddleName] [nvarchar] (30) NULL,
[MaidenName] [nvarchar] (20) NULL,
[LastName] [nvarchar] (100) NOT NULL,
[SuffixCode] [nvarchar] (10) NULL,
[NickName] [nvarchar] (25) NULL,
[AddressLineOne] [nvarchar] (100) NULL,
[AddressLineTwo] [nvarchar] (100) NULL,
[CityName] [nvarchar] (30) NULL,
[StateCode] [nvarchar] (30) NULL,
[ZipCode] [nvarchar] (15) NULL CONSTRAINT [DF_People_ZipCode] DEFAULT (''),
[CountryName] [nvarchar] (40) NULL,
[StreetName] [nvarchar] (40) NULL,
[CellPhone] [nvarchar] (20) NULL,
[WorkPhone] [nvarchar] (20) NULL,
[EmailAddress] [nvarchar] (150) NULL,
[OtherPreviousChurch] [nvarchar] (120) NULL,
[OtherNewChurch] [nvarchar] (60) NULL,
[SchoolOther] [nvarchar] (100) NULL,
[EmployerOther] [nvarchar] (120) NULL,
[OccupationOther] [nvarchar] (120) NULL,
[HobbyOther] [nvarchar] (40) NULL,
[SkillOther] [nvarchar] (40) NULL,
[InterestOther] [nvarchar] (40) NULL,
[LetterStatusNotes] [nvarchar] (3000) NULL,
[Comments] [nvarchar] (3000) NULL,
[ChristAsSavior] [bit] NOT NULL CONSTRAINT [DF_PEOPLE_TBL_CHRIST_AS_SAVIOR] DEFAULT ((0)),
[MemberAnyChurch] [bit] NULL,
[InterestedInJoining] [bit] NOT NULL CONSTRAINT [DF_PEOPLE_TBL_INTERESTED_IN_JOINING] DEFAULT ((0)),
[PleaseVisit] [bit] NOT NULL CONSTRAINT [DF_PEOPLE_TBL_PLEASE_VISIT] DEFAULT ((0)),
[InfoBecomeAChristian] [bit] NOT NULL CONSTRAINT [DF_PEOPLE_TBL_INFO_BECOME_A_CHRISTIAN] DEFAULT ((0)),
[ContributionsStatement] [bit] NOT NULL CONSTRAINT [DF_PEOPLE_TBL_CONTRIBUTIONS_STATEMENT] DEFAULT ((0)),
[ModifiedBy] [int] NULL,
[ModifiedDate] [datetime] NULL,
[PictureId] [int] NULL,
[ContributionOptionsId] [int] NULL,
[PrimaryCity] [nvarchar] (30) NULL,
[PrimaryZip] [nvarchar] (15) NULL,
[PrimaryAddress] [nvarchar] (100) NULL,
[PrimaryState] [nvarchar] (20) NULL,
[HomePhone] [nvarchar] (20) NULL,
[SpouseId] [int] NULL,
[PrimaryAddress2] [nvarchar] (100) NULL,
[PrimaryResCode] [int] NULL,
[PrimaryBadAddrFlag] [int] NULL,
[LastContact] [datetime] NULL,
[Grade] [int] NULL,
[CellPhoneLU] [char] (7) NULL,
[WorkPhoneLU] [char] (7) NULL,
[BibleFellowshipClassId] [int] NULL,
[CampusId] [int] NULL,
[CellPhoneAC] [char] (3) NULL,
[CheckInNotes] [nvarchar] (1000) NULL,
[Age] AS ((datepart(year,isnull([DeceasedDate],getdate()))-[BirthYear])-case  when [BirthMonth]>datepart(month,isnull([DeceasedDate],getdate())) OR [BirthMonth]=datepart(month,isnull([DeceasedDate],getdate())) AND [BirthDay]>datepart(day,isnull([DeceasedDate],getdate())) then (1) else (0) end),
[AltName] [nvarchar] (100) NULL,
[CustodyIssue] [bit] NULL,
[OkTransport] [bit] NULL,
[BDate] AS (dateadd(month,(([BirthYear]-(1900))*(12)+[BirthMonth])-(1),[Birthday]-(1))),
[HasDuplicates] [bit] NULL,
[FirstName2] [nvarchar] (50) NULL,
[EmailAddress2] [nvarchar] (60) NULL,
[SendEmailAddress1] [bit] NULL,
[SendEmailAddress2] [bit] NULL,
[NewMemberClassDate] [datetime] NULL,
[PrimaryCountry] [nvarchar] (40) NULL,
[ReceiveSMS] [bit] NOT NULL CONSTRAINT [DF_People_ReceiveSMS] DEFAULT ((0)),
[DoNotPublishPhones] [bit] NULL,
[IsDeceased] AS (CONVERT([bit],case  when [DeceasedDate] IS NULL then (0) else (1) end,(0))),
[SSN] [nvarchar] (50) NULL,
[DLN] [nvarchar] (75) NULL,
[DLStateID] [int] NULL,
[HashNum] AS (checksum([FirstName]+[LastName])),
[PreferredName] AS (case  when [Nickname]<>'' then [nickname] else [FirstName] end),
[Name2] AS ((([LastName]+', ')+case  when [Nickname]<>'' then [nickname] else [FirstName] end)+case  when len([SuffixCode])>(0) then ', '+[SuffixCode] else '' end),
[Name] AS (((case  when [Nickname]<>'' then [nickname] else isnull([FirstName],'') end+' ')+[LastName])+case  when len([SuffixCode])>(0) then ', '+[SuffixCode] else '' end),
[ElectronicStatement] [bit] NULL
) ON [PRIMARY]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
