CREATE TABLE [dbo].[MobileAppIcons]
(
[id] [int] NOT NULL IDENTITY(1, 1),
[setID] [int] NOT NULL CONSTRAINT [DF_MobileAppIcons_setID] DEFAULT ((0)),
[actionID] [int] NOT NULL CONSTRAINT [DF_MobileAppIcons_type] DEFAULT ((0)),
[url] [nvarchar] (200) NOT NULL CONSTRAINT [DF_MobileAppIcons_url] DEFAULT ('')
)
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
