
CREATE VIEW [dbo].[OrgsWithFees]
AS
(
	SELECT 
		OrganizationId
	FROM dbo.Organizations
WHERE dbo.OrgFee(OrganizationId) > 0
)
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
