ALTER TABLE [dbo].[FamilyExtra] ADD CONSTRAINT [PK_FamilyExtra_1] PRIMARY KEY CLUSTERED  ([FamilyId], [Field])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
