ALTER TABLE [dbo].[MergeHistory] ADD CONSTRAINT [PK_MergeHistory] PRIMARY KEY CLUSTERED  ([FromId], [ToId], [Dt])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
