ALTER TABLE [dbo].[PeopleExtra] ADD CONSTRAINT [PK_PeopleExtra_1] PRIMARY KEY CLUSTERED  ([PeopleId], [Field], [Instance])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
