CREATE TABLE [dbo].[EmailResponses]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[EmailQueueId] [int] NOT NULL,
[PeopleId] [int] NOT NULL,
[Type] [char] (1) NOT NULL,
[Dt] [datetime] NOT NULL
)
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
