CREATE TABLE [dbo].[MobileAppIconSets]
(
[id] [int] NOT NULL IDENTITY(1, 1),
[name] [nvarchar] (100) NOT NULL CONSTRAINT [DF_MobileAppIconSets_name] DEFAULT (''),
[active] [bit] NOT NULL CONSTRAINT [DF_MobileAppIconSets_active] DEFAULT ((0))
)
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
