CREATE FUNCTION [dbo].[IsValidEmail] (@string [nvarchar] (100))
RETURNS [bit]
WITH EXECUTE AS CALLER
EXTERNAL NAME [CmsDataSqlClr].[CmsDataSqlClr.UserDefinedFunctions].[IsValidEmail]
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
