CREATE FUNCTION [dbo].[DonorTotalUnits](@t DonorTotalsTable READONLY, @attr INT = NULL)
RETURNS INT
AS
BEGIN
	DECLARE @ret INT
	SELECT @ret = COUNT(*) FROM @t WHERE attr = @attr OR @attr IS NULL
	RETURN @ret
END
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
