SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE FUNCTION [dbo].[IsValidEmail] (@string [nvarchar] (100))
RETURNS [bit]
WITH EXECUTE AS CALLER
EXTERNAL NAME [CmsDataSqlClr].[CmsDataSqlClr.UserDefinedFunctions].[IsValidEmail]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO
