ALTER TABLE [dbo].[Duplicate] ADD CONSTRAINT [PK_Duplicate] PRIMARY KEY CLUSTERED  ([id1], [id2])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
