ALTER TABLE [dbo].[CheckedBatches] ADD CONSTRAINT [PK_CheckedBatches] PRIMARY KEY CLUSTERED  ([BatchRef])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
