ALTER TABLE [dbo].[ContentKeyWords] ADD CONSTRAINT [PK_ContentKeyWords] PRIMARY KEY CLUSTERED  ([Id], [Word])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
