ALTER TABLE [dbo].[FamilyCheckinLock] ADD CONSTRAINT [PK_FamilyCheckinLock] PRIMARY KEY CLUSTERED  ([FamilyId])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
