CREATE NONCLUSTERED INDEX [_dta_index_Downline_13_656630028__K1_K2_K6] ON [dbo].[Downline] ([CategoryId], [DownlineId], [DiscipleId])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
