CREATE FUNCTION [dbo].[AgeInMonths](@pid int, @asof DATETIME)
RETURNS int
AS
BEGIN
	DECLARE @bd DATETIME = dbo.Birthday(@pid)
	DECLARE @mos INT
		= DATEDIFF(MONTH, @bd, @asof) - IIF(DATEPART(DAY, @asof) < DATEPART(DAY, @bd), 1, 0)
	RETURN @mos
END
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
