CREATE TABLE [dbo].[SecurityCodes]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[Code] [char] (4) NOT NULL,
[DateUsed] [datetime] NULL
)
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
