CREATE FUNCTION [dbo].[SpaceToNull](@s nvarchar(MAX))
RETURNS nvarchar(MAX)
AS
BEGIN
	
	IF @s IS NULL
		RETURN NULL
	IF LEN(@s) = 0
		RETURN NULL
	RETURN @s;
END
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
