CREATE TABLE [dbo].[CardIdentifiers]
(
[Id] [nvarchar] (80) NOT NULL,
[PeopleId] [int] NULL,
[CreatedOn] [datetime] NULL
)
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
