CREATE VIEW [dbo].[LastName]
AS
SELECT LastName, COUNT(*) AS [count] FROM dbo.People GROUP BY LastName
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
