CREATE CLUSTERED INDEX [_dta_index_People_c_9_1770345967__K1_K48] ON [dbo].[People] ([PeopleId], [DeceasedDate])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
