CREATE NONCLUSTERED INDEX [IX_Coupons_1] ON [dbo].[Coupons] ([DivId], [OrgId])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
