ALTER TABLE [dbo].[BundleHeader] ADD CONSTRAINT [BUNDLE_HEADER_PK] PRIMARY KEY NONCLUSTERED  ([BundleHeaderId])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
