ALTER TABLE [dbo].[VolRequest] ADD CONSTRAINT [PK_VolRequest] PRIMARY KEY CLUSTERED  ([MeetingId], [RequestorId], [Requested], [VolunteerId])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
