ALTER TABLE [dbo].[PeopleCanEmailFor] ADD CONSTRAINT [PK_PeopleCanEmailFor] PRIMARY KEY CLUSTERED  ([CanEmail], [OnBehalfOf])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
