ALTER TABLE [dbo].[Ministries] ADD CONSTRAINT [PK_MINISTRIES_TBL] PRIMARY KEY CLUSTERED  ([MinistryId])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
