ALTER TABLE [dbo].[ManagedGiving] ADD CONSTRAINT [PK_ManagedGiving] PRIMARY KEY CLUSTERED  ([PeopleId])
GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
